os: linux
dist: xenial
language: generic

cache:
  directories:
    - "$HOME/.stack"

services:
  - docker

addons:
  apt:
    update: true

before_install:
  - docker pull thalesmg/rpw_test:v2.1
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - stack --no-terminal --install-ghc build --only-dependencies

script:
  - stack --no-terminal install --flag "rpw:rpw_dist" --local-bin-path "$PWD"
  - docker run --rm -e userid=$UID -v $PWD:/mnt thalesmg/rpw_test:v2.1 /mnt/run_tests
  - sha256sum rpw > rpw.sha256.txt

deploy:
  provider: releases
  token:
    secure: "C+zORUGq6N8HLexQI/LblQhowS82nAHEOdFzMCbZwa/bZuX24QYyE3QiXRs/kd2DleTC2X0Jcbgivng09ajZTRoiv2itdROGBUIZOu8wCAvtLeCx02K2qAylD667Urc2F/e0ts2pHWSwfVve4IKDs8525GsuCKhCkntCBOfMp+EyiZf2ZBA4OWvFrNlETHrMBUWthHrWn51mt5vq2PUjkT6GFngHwQ0p0vt03m+AzObtwJtgSJzJT291NatN06CLw+KMZPw3p6ZffAvLOwTIk1ZXfZpPUqZXFK8bIyHYmx4JFT14M9YjpeuZtisZHf44v0CJJ252FnoGaEbATfRPoeXs6YlTXwORjS5IwdtOkQiF4vmaLnOs4zK7DumlXuWWGwfqPyJgf2XZEWzUrHtIYNZ+XCho4wctp4sSuVuBIbJ81NsHynYp93nB+JS9abE6NhZ8xGLb8Nx1HbAshrwz1pZGX4KioZqZpkviUmpdEouE9h60W2/1LO4MVRlQ6fBwIKGjvIWM/L9AE8l1ikrKT+DvEN/jzH8+jNVXfrgrlaFwhCdyn+6NWb/4DY93uyEiF6ZQ/c8i/X4nZ5FnFlxwpT/ki6WSEvc8j1xNs5SmlX634jIaOaQdl+Bs5BIhn4WG7Tq88zZvUH7EKUlhZo8qqlB2i8RytdOAbA3znabHFhU="
  edge: yes
  file:
    - rpw
    - rpw.sha256.txt
  cleanup: false
  on:
    repo: thalesmg/rpw
    branch: master
    tags: true
