#!/usr/bin/expect -f

set prompt ":"
set timeout 1
set curdir $env(PWD)

spawn -noecho env ZDOTDIR=$env(PWD)/tests/ rpw zsh

send "unset PROMPT_COMMAND; PS1=:\r"
expect *
send \n
expect $prompt

send "cat\r"
expect {
    "cat\r\n" { }
    timeout { puts "timeout after command"; exit 1 }
}
expect {
    -re "^$" { }
    timeout { puts "timeout waiting for cat"; exit 1 }
}
send "a"
expect -re "^a$"
send \r
expect \r\n
expect {
    -re "\r\na\r\n$" { }
    timeout { puts "timeout expecting input"; exit 1 }
}

# C-c
send \u0003

# rpw must be still alive
expect {
    $prompt { }
    timeout { puts "error after sending C-c"; exit 1 }
}
send "echo \$PWD\r"
expect {
    "echo \$PWD" { }
    timeout { puts "timeout expecting last command"; exit 1 }
}
expect {
    "$curdir" { puts "OK" }
    timeout { "timeout expecting last ouptut"; exit 1 }
}
