#!/usr/bin/expect -f

set prompt ":$"
set timeout 1

spawn -noecho rpw bash

send "unset PROMPT_COMMAND; PS1=:\r"
expect *
expect {
    -re $prompt { }
    timeout { puts "startup error"; exit 1 }
}

send "echo \$-\r"
expect {
    "echo \$-\r\n" { }
    timeout { puts "timeout waiting for command"; exit 1 }
}
expect {
    "himBHs\r\n" { }
    timeout { puts "timeout while waiting echo"; exit 1 }
}
expect {
    -re $prompt { puts "OK" }
    timeout { puts "timeout after echo"; exit 1 }
}
